import { useState } from "react";
import { AlertTriangle, FileCheck, Scale } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";

const ACKNOWLEDGEMENT_VERSION = "1.0";

const LEGAL_DISCLAIMER = `The documents generated by this software are drafts intended solely for informational and organizational purposes. They do not constitute legal advice and are not a substitute for independent legal counsel.

Before filing, submitting, or relying on any court document, you must have it reviewed, edited, and approved by a licensed attorney admitted to practice in the appropriate jurisdiction.

The use of this tool does not create an attorney-client relationship. The developers, operators, and any affiliated parties of this software assume no liability for errors, omissions, or any consequences resulting from the use of these generated documents.

By proceeding, you acknowledge and accept full responsibility for any use or submission of documents prepared with this tool.`;

interface PreSubmissionReviewModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  caseId: string;
  documentId: string;
  onConfirm: () => void;
}

export default function PreSubmissionReviewModal({
  open,
  onOpenChange,
  caseId,
  documentId,
  onConfirm,
}: PreSubmissionReviewModalProps) {
  const [reviewedChecked, setReviewedChecked] = useState(false);
  const [understandChecked, setUnderstandChecked] = useState(false);

  const logAcknowledgementMutation = useMutation({
    mutationFn: async () => {
      await apiRequest("POST", `/api/cases/${caseId}/documents/${documentId}/acknowledge`, {
        acknowledgementVersion: ACKNOWLEDGEMENT_VERSION,
        reviewedChecked,
        understandChecked,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/cases", caseId, "activity"] });
      onConfirm();
      handleClose();
    },
  });

  const handleClose = () => {
    setReviewedChecked(false);
    setUnderstandChecked(false);
    onOpenChange(false);
  };

  const handleProceed = () => {
    logAcknowledgementMutation.mutate();
  };

  const canProceed = reviewedChecked && understandChecked;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Scale className="w-5 h-5 text-amber-500" />
            Pre-Submission Review Required
          </DialogTitle>
          <DialogDescription>
            Please review the following disclaimer before exporting this document.
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[300px] pr-4">
          <div className="bg-muted/50 p-4 rounded-md border border-muted-foreground/20">
            <div className="flex items-start gap-2 mb-3">
              <AlertTriangle className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" />
              <h4 className="font-medium text-sm">Legal Disclaimer</h4>
            </div>
            <p className="text-sm text-muted-foreground whitespace-pre-line leading-relaxed">
              {LEGAL_DISCLAIMER}
            </p>
          </div>
        </ScrollArea>

        <div className="space-y-4 mt-4">
          <div className="flex items-start space-x-3">
            <Checkbox
              id="reviewed"
              checked={reviewedChecked}
              onCheckedChange={(checked) => setReviewedChecked(checked === true)}
              data-testid="checkbox-reviewed"
            />
            <label
              htmlFor="reviewed"
              className="text-sm leading-relaxed cursor-pointer"
            >
              I have reviewed this document and verified its accuracy to the best of my knowledge.
            </label>
          </div>

          <div className="flex items-start space-x-3">
            <Checkbox
              id="understand"
              checked={understandChecked}
              onCheckedChange={(checked) => setUnderstandChecked(checked === true)}
              data-testid="checkbox-understand"
            />
            <label
              htmlFor="understand"
              className="text-sm leading-relaxed cursor-pointer"
            >
              I understand this document is a draft and must be reviewed by a licensed attorney before filing.
            </label>
          </div>
        </div>

        <DialogFooter className="gap-2 sm:gap-0 mt-4">
          <Button
            variant="outline"
            onClick={handleClose}
            data-testid="button-cancel-export"
          >
            Cancel
          </Button>
          <Button
            onClick={handleProceed}
            disabled={!canProceed || logAcknowledgementMutation.isPending}
            className="gap-2"
            data-testid="button-proceed-export"
          >
            <FileCheck className="w-4 h-4" />
            {logAcknowledgementMutation.isPending ? "Processing..." : "Proceed to Export"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
